# Generated by Django 4.2.7 on 2026-05-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('type_user', models.CharField(choices=[('etudiant', 'Étudiant'), ('professeur', 'Professeur'), ('personnel', 'Personnel')], default='etudiant', max_length=20)),
                ('matricule', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'utilisateurs',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
