# Generated by Django 4.2.7 on 2026-05-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('auteur', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('categorie', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('annee', models.IntegerField(blank=True, null=True)),
                ('editeur', models.CharField(blank=True, max_length=150)),
                ('stock_total', models.IntegerField(default=1)),
                ('stock_dispo', models.IntegerField(default=1)),
                ('couverture', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'livres',
                'ordering': ['titre'],
            },
        ),
    ]
